#! /bin/sh

sxhkd &
compton &
redshift &
#polybar example2 &
feh --bg-fill /home/fer/Imágenes/Fondos\ de\ escritorio/kuro.jpg &
xinput set-prop "ELAN0504:01 04F3:312A Touchpad" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "ELAN0504:01 04F3:312A Touchpad" "libinput Tapping Enabled" 1 &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap          0
bspc config normal_border_color "#1a1a1a"
bspc config active_border_color "#bd93aa"
bspc config focused_border_color "#a77370"
bspc config presel_feedback_color "#6272a4"

bspc config pointer_motion_interval 1

bspc config top_padding 22 &
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a \* rectangle 1600x900+0+0 center=true


bspc rule -a Zathura state=tiled



