#! /bin/sh

sxhkd &
compton &
redshift &
#polybar example2 &
feh --bg-fill /home/fer/Imágenes/Fondos\ de\ escritorio/nordify/os3.png &
sct 1700 &
xinput set-prop 13 319 1 &
xinput set-prop 13 337 1 &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         3
bspc config window_gap          12
bspc config normal_border_color "#0f0a0a"
bspc config active_border_color "#bd93aa"
bspc config focused_border_color "#a77370"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
