#!/bin/bash
# Prints the current volume or 🔇 if muted.
[ $(pamixer --get-mute) = true ] && echo "婢" && exit
#vol=$(amixer get Master |grep % |awk '{print $5}'|sed 's/[^0-9\%]//g' | head -n 1)
#vol=$(awk '/%/ {gsub(/[\[\]]/,""); print $4}' <(amixer sget Master) | head -n 1)
#vol=$(amixer get Master | egrep -o '[0-9]{1,3}%' | head -n 1)
#amixer get Master |grep % |awk '{print $5}'|sed 's/[^0-9\%]//g'

#perc=$($vol | head -c 2)

icon=""
#echo " $icon $vol "
echo " $icon "
